-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE AQUACULTURE_WATER_QUALITY;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.FARMS (
  FARM_ID VARCHAR(20) NOT NULL, FARM_NAME VARCHAR(200), PROVINCE VARCHAR(50), AREA_HA FLOAT, FARM_TYPE VARCHAR(30), CERTIFICATION VARCHAR(50), STATUS VARCHAR(20), ESTABLISHED_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PONDS (
  POND_ID VARCHAR(20) NOT NULL, FARM_ID VARCHAR(20), POND_NAME VARCHAR(100), AREA_HA FLOAT, SPECIES VARCHAR(50), STOCKING_DENSITY INT, CYCLE_START DATE, STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.HARVESTS (
  HARVEST_ID VARCHAR(30) NOT NULL, PLANTATION_ID VARCHAR(20), HARVEST_DATE DATE, FFB_TONNES FLOAT, RIPE_PCT FLOAT, WORKERS INT, COST_PER_TONNE FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.WATER_READINGS (
  READING_ID VARCHAR(30) NOT NULL, POND_ID VARCHAR(20), READING_TIME TIMESTAMP, PH FLOAT, DO_MG_L FLOAT, TEMPERATURE_C FLOAT, SALINITY_PPT FLOAT, AMMONIA_MG_L FLOAT, TURBIDITY_NTU FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
