-- Generated from generator/demo_specs/aws-vietnam-aquaculture-water-quality.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-aquaculture-water-quality
-- This is the schema that is actually deployed for VIETNAM_AQUACULTURE_WATER_QUALITY.

-- Alerts fire on the bottom tail of Water Quality Index
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_WATER_QUALITY_INDEX) AS T
  FROM RAW.METRICS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_WATER_QUALITY_INDEX <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_WATER_QUALITY_INDEX), 2) AS AVG_WATER_QUALITY_INDEX,
  ROUND(AVG(f.KPI_DISSOLVED_OXYGEN_AVG), 2) AS AVG_DISSOLVED_OXYGEN,
  ROUND(AVG(f.KPI_PH_AVG), 2) AS AVG_PH,
  ROUND(AVG(f.KPI_AMMONIA_LEVEL), 2) AS AVG_AMMONIA_LEVEL,
  ROUND(AVG(f.KPI_TEMPERATURE), 2) AS AVG_TEMPERATURE
FROM RAW.METRICS f
JOIN RAW.DOCUMENTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_WATER_QUALITY_INDEX), 2) AS AVG_WATER_QUALITY_INDEX,
  ROUND(AVG(f.KPI_DISSOLVED_OXYGEN_AVG), 2) AS AVG_DISSOLVED_OXYGEN,
  ROUND(AVG(f.KPI_PH_AVG), 2) AS AVG_PH,
  ROUND(AVG(f.KPI_AMMONIA_LEVEL), 2) AS AVG_AMMONIA_LEVEL,
  ROUND(AVG(f.KPI_TEMPERATURE), 2) AS AVG_TEMPERATURE
FROM RAW.METRICS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_WATER_QUALITY_INDEX) AS KPI_WATER_QUALITY_INDEX, AVG(KPI_DISSOLVED_OXYGEN_AVG) AS KPI_DISSOLVED_OXYGEN_AVG, AVG(KPI_PH_AVG) AS KPI_PH_AVG, AVG(KPI_AMMONIA_LEVEL) AS KPI_AMMONIA_LEVEL, AVG(KPI_TEMPERATURE) AS KPI_TEMPERATURE FROM RAW.METRICS),
     en AS (SELECT SUM(KPI_DISEASE_ALERTS) AS KPI_DISEASE_ALERTS, SUM(KPI_PONDS_MONITORED) AS KPI_PONDS_MONITORED FROM RAW.DOCUMENTS)
  SELECT 1 AS SORT_ORDER, 'Water Quality Index' AS TITLE, KPI_WATER_QUALITY_INDEX AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_WATER_QUALITY_INDEX), 1) AS DECIMAL(38,1))) || '/10' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Dissolved Oxygen (Avg)' AS TITLE, KPI_DISSOLVED_OXYGEN_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DISSOLVED_OXYGEN_AVG), 1) AS DECIMAL(38,1))) || ' ' || 'mg/L' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Disease Alerts' AS TITLE, KPI_DISEASE_ALERTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DISEASE_ALERTS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Ponds Monitored' AS TITLE, KPI_PONDS_MONITORED AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_PONDS_MONITORED)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'pH (Avg)' AS TITLE, KPI_PH_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PH_AVG), 1) AS DECIMAL(38,1))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Ammonia Level' AS TITLE, KPI_AMMONIA_LEVEL AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AMMONIA_LEVEL), 2) AS DECIMAL(38,2))) || ' ' || 'mg/L' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Temperature' AS TITLE, KPI_TEMPERATURE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TEMPERATURE), 1) AS DECIMAL(38,1))) || '°C' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
